# print(len('hello'))
# print(len('I am'))
# my_string = "Hello World"
# print(my_string)
# print(my_string[0])
# print(my_string[8])
# print(my_string[-3])
# print(my_string[-1])
my_string = 'abcdefghijk'
# print(my_string)
# print(my_string[2:])
# print(my_string[:3])
# print(my_string[3:6])
print(my_string[1:3])
print(my_string[3::3])
print(my_string[::-1])
print("Hello World" [8])
